<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Chronicle</title>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                line-height: 1;
                margin-bottom: 0;
            }
            h1 img {
                height: 1em;
                vertical-align: text-bottom;
            }

            hr {
                width: 75%;
                margin-left: auto;
                margin-right: auto;
            }
        </style>
    </head>
    <body>
        <h1><img src="chronicle-logo.svg" />Chronicle</h1>
        <p>
            Chronicle is a software security project created by
            <a href="https://paragonie.com">the PHP security and cryptography team at Paragon Initiative Enterprises</a>.
        </p>
        <p>
            <a href="./chronicle">Click Here for the Chronicle API</a>
        </p>
        <p>
            Please report any problems on <a href="https://github.com/paragonie/chronicle">Github</a>.
        </p>
        <hr />
        <p>Powered by
            <a href="https://secure.php.net">PHP 7</a>,
            <a href="http://www.slimframework.com">Slim</a>,
            <a href="https://github.com/paragonie/sapient">Sapient</a>,
            <a href="https://github.com/paragonie/blakechain">Blakechain</a>,
            <a href="https://github.com/paragonie/sodium_compat">sodium_compat</a>, and
            <a href="https://download.libsodium.org/doc/">libsodium</a>.
        </p>
    </body>
</html>
